// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdkKDtU5uOhZ4LyDAUm2qdDlgjyvHCoxo',
    appId: '1:596166230224:web:3f790bf236d486f3a15ed5',
    messagingSenderId: '596166230224',
    projectId: 'smart-timer-app',
    authDomain: 'smart-timer-app.firebaseapp.com',
    storageBucket: 'smart-timer-app.firebasestorage.app',
    measurementId: 'G-33S0W0X9HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMJLbgolEBV7MY-O-Ibi9s_iBkNxvGUbs',
    appId: '1:596166230224:android:fbb50862266e3eeda15ed5',
    messagingSenderId: '596166230224',
    projectId: 'smart-timer-app',
    storageBucket: 'smart-timer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAerBip2fIQyMSB-RqfZ9zMBQS-I8pcxUc',
    appId: '1:596166230224:ios:479696b90d129421a15ed5',
    messagingSenderId: '596166230224',
    projectId: 'smart-timer-app',
    storageBucket: 'smart-timer-app.firebasestorage.app',
    iosBundleId: 'com.example.smartTimerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAerBip2fIQyMSB-RqfZ9zMBQS-I8pcxUc',
    appId: '1:596166230224:ios:479696b90d129421a15ed5',
    messagingSenderId: '596166230224',
    projectId: 'smart-timer-app',
    storageBucket: 'smart-timer-app.firebasestorage.app',
    iosBundleId: 'com.example.smartTimerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdkKDtU5uOhZ4LyDAUm2qdDlgjyvHCoxo',
    appId: '1:596166230224:web:f6d3a09b7695bcaba15ed5',
    messagingSenderId: '596166230224',
    projectId: 'smart-timer-app',
    authDomain: 'smart-timer-app.firebaseapp.com',
    storageBucket: 'smart-timer-app.firebasestorage.app',
    measurementId: 'G-E3XZ0ZRYX3',
  );
}
