// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATsIavDc5BnGdorR9BUmRpV4a-F6Q1sCU',
    appId: '1:100780475148:web:48555cecfab24bc4047f29',
    messagingSenderId: '100780475148',
    projectId: 'smart-timer-app-7da95',
    authDomain: 'smart-timer-app-7da95.firebaseapp.com',
    storageBucket: 'smart-timer-app-7da95.firebasestorage.app',
    measurementId: 'G-P42Q4DPCJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhhPjZJq1G47heh7sCDZpIybD0UXuwLV0',
    appId: '1:100780475148:android:087411f4a69301a0047f29',
    messagingSenderId: '100780475148',
    projectId: 'smart-timer-app-7da95',
    storageBucket: 'smart-timer-app-7da95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOAPIstBbeywzOWYYMxe-bdlASjONT-4Q',
    appId: '1:100780475148:ios:140d08627e1824f2047f29',
    messagingSenderId: '100780475148',
    projectId: 'smart-timer-app-7da95',
    storageBucket: 'smart-timer-app-7da95.firebasestorage.app',
    iosBundleId: 'com.example.smartTimerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOAPIstBbeywzOWYYMxe-bdlASjONT-4Q',
    appId: '1:100780475148:ios:140d08627e1824f2047f29',
    messagingSenderId: '100780475148',
    projectId: 'smart-timer-app-7da95',
    storageBucket: 'smart-timer-app-7da95.firebasestorage.app',
    iosBundleId: 'com.example.smartTimerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATsIavDc5BnGdorR9BUmRpV4a-F6Q1sCU',
    appId: '1:100780475148:web:994a73143491d08a047f29',
    messagingSenderId: '100780475148',
    projectId: 'smart-timer-app-7da95',
    authDomain: 'smart-timer-app-7da95.firebaseapp.com',
    storageBucket: 'smart-timer-app-7da95.firebasestorage.app',
    measurementId: 'G-2P76KM5LYX',
  );
}
